version: '3.5'
services:
    db:
      container_name: db_noctua
      image: mongo
      command: mongod --quiet --logpath /dev/null
      ports: 
          - 27017:27017

    api:
        depends_on:
            - db
        container_name: backend_noctua
        environment:
            - DATABASE_URL=mongodb://db/noctua
        build:
            context: ./server
        ports:
            - "5000:5000"
        command: yarn start
    
    
    front: 
        environment:
            - CHOKIDAR_USEPOLLING=true
        container_name: frontend_noctua
        build:
            context: ./front
        ports:
            - "3000:80"
        depends_on:
            - api
